In [4]:
def norm_feature(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - n_min) / (n_max - n_min)

    return data

In [9]:
data = [10, 25, 15, 30, 50]

n_data = norm_feature(data)
n_data

[0.0, 0.375, 0.125, 0.5, 1.0]

In [10]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [18]:
data = [[100, 0.01],
        [8, 0.05],
        [50, 0.005]
        ]

np_data = np.asarray(data)
mm_scaler = MinMaxScaler()
mm_data= mm_scaler.fit_transform(data)
mm_data

array([[1.        , 0.11111111],
       [0.        , 1.        ],
       [0.45652174, 0.        ]])

In [30]:
import pstats
from statistics import mean, pstdev, stdev


def std_feature(data):
    baris_data = data.shape[0]
    kolom_data =  data.shape[1]

    for i in range(0, baris_data):
        for j in range(0, kolom_data):
            data[i][j] = (data[i][j] - mean(data[:, j])) / pstdev(data[:, j])
    
    return data

In [33]:
data = [[100, 0.001],
        [8, 0.05],
        [50, 0.005],
        [88, 0.07],
        [4, 0.1]
        ]
data_1 = [100, 0.01]

data = np.asarray(data)

#std_data = std_feature(data)
#std_data

In [34]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

std_data = ss_scaler.fit_transform(data)
std_data

array([[ 1.26398112, -1.16389967],
       [-1.06174414,  0.12639634],
       [ 0.        , -1.05856939],
       [ 0.96062565,  0.65304778],
       [-1.16286263,  1.44302493]])

In [37]:
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
ordinal_encoder = OrdinalEncoder()

oe = [['POLINEMA'],
        ['PENS'],
        ['PNJ'],
        ['PNP'],
        ['POLBAN']
]

ord_oe = ordinal_encoder.fit_transform(oe)
oh_oe = OneHotEncoder().fit_transform(oe)
oh_oe.toarray()

array([[0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [42]:
corpus = [
            'the house had a tiny little mouse',
            'the cat saw the mouse',
            'the mouse ran away from the house',
            'the cat finally ate the mouse',
            'the end of the mouse story'
]

In [50]:
from unittest import result
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(stop_words='english')
result = vect.fit_transform(corpus)
#print(vect.get_feature_names())
#print(result.toarray())
result.todense()

matrix([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.4755751 , 0.58946308, 0.28088232, 0.        , 0.        ,
         0.        , 0.58946308],
        [0.        , 0.        , 0.58873218, 0.        , 0.        ,
         0.        , 0.        , 0.34771471, 0.        , 0.72971837,
         0.        , 0.        ],
        [0.        , 0.58946308, 0.        , 0.        , 0.        ,
         0.4755751 , 0.        , 0.28088232, 0.58946308, 0.        ,
         0.        , 0.        ],
        [0.58946308, 0.        , 0.4755751 , 0.        , 0.58946308,
         0.        , 0.        , 0.28088232, 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.67009179, 0.        ,
         0.        , 0.        , 0.31930233, 0.        , 0.        ,
         0.67009179, 0.        ]])

In [43]:
sentences = 'The house had a tiny little mouse. The cat saw the mouse .The mouse ran away from the house'

stc_split = sentences.split('.')
stc_split

['The house had a tiny little mouse',
 ' The cat saw the mouse ',
 'The mouse ran away from the house']